<?php
/**
 *
 * @category Sashas
 * @package Sashas_InstagramWidget
 * @author Sashas IT Support <support@sashas.org>
 * @copyright 2007-2016 Sashas IT Support Inc. (http://www.sashas.org)
 * @license http://opensource.org/licenses/GPL-3.0 GNU General Public License, version 3 (GPL-3.0)
 * @link http://www.extensions.sashas.org/instagram-widget.html
 */
?> 
<?php $posts_info=$this->getPosts(); ?>
<?php $enable_popup=Mage::getStoreConfig('instagramwidget/instagramwidget_group/show_full_popup');?> 
<?php $show_caption=Mage::getStoreConfig('instagramwidget/instagramwidget_group/show_caption');?> 
<?php
$instagram_link=0;
 if (!$enable_popup)
    $instagram_link=Mage::getStoreConfig('instagramwidget/instagramwidget_group/open_instagram');
?>

<?php if (count($posts_info->getData('data'))):?>
<div class="block block-instagram-widget">
	<div class="block-title">
		<strong><span><?php echo $this->getBlockTitle();?></span></strong>
	</div>
	<div class="block-content"> 
	    <?php /* $post['link'] - link to instagram post */?>	     
		<?php  foreach ($posts_info->getData('data') as $post): ?> 
			 <div class="instagram-image" style="width: <?php echo 100/count($posts_info->getData('data'))-2;  ?>%">  
				<?php foreach ($post['images'] as $size=>$image): ?> 
									 				
					<?php if ($size==$this->getImageResolution()):?>
 
						<?php if ($enable_popup):?>						 
							<a <?php if ($popup_function=='iframe'): ?> content=" " <?php endif;?> class="instagram-widget-link" rel="gallery1"
							href="<?php  echo $post['images']['standard_resolution']['url']; ?>"
							title="<?php if ($show_caption) echo $post['caption']['text']; ?>"> 
						<?php endif;?>
						<?php if ($instagram_link):?>  
							<a href="<?php echo $post['link'];?>" target="_blank"  title="<?php echo $post['caption']['text']; ?>" />
						<?php endif;?>					
					 		<img src="<?php echo $image['url']; ?>" />
					 		
						<?php if ($enable_popup || $instagram_link):?>
							</a>
						<?php endif;?>		
									 	
					<?php endif; ?>
				<?php endforeach;?>
			</div>
		<?php endforeach;?>
		</div>
</div>
<?php endif; ?>


<?php if ($enable_popup): ?>
<script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery(".instagram-widget-link").fancybox({ 
			openEffect	: 'none',
			closeEffect	: 'none'
		});
	});
</script>
<?php endif;?>