<?php 
echo $this->getChildHtml('new_products');
?>

<div id="instafeed-head"> Instagram: <a href="https://www.instagram.com/aloha.esthetics/?ref=badge">@aloha.esthetics</a>
</div>
<div id="instafeed"></div>


<script type="text/javascript">
var userFeed = new Instafeed({
    get: 'user',
    limit: '6',
    resolution: 'low_resolution',
    userId: '2976525140',
    accessToken: '2976525140.467ede5.906371d6d5df4ec3ac06d8ba760219ad',
    template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /></a>'
});
userFeed.run();

</script>
