<div class='pads'>
<!-- <div class='image-pad left'>
	<div class='pad-text'><h3>Eyelash Extensions</h3>
		<h3>Lashes & Adhesive </h3>
	</div>
	<img src="<?php echo $this->getSkinUrl('images/eyelash_extensions1.png', array('_secure'=>true));?>"/>
</div>
<div class='image-pad'>
	<div class='pad-text'><h3>Waxing Service</h3>
		<h3>Face.Lips.Eyebrows.Legs.Underarms</h3>
	</div>
	<img src="<?php echo $this->getSkinUrl('images/waxing.png', array('_secure'=>true));?>"/>
</div> -->
<div class="image-pad flexslider">
<?php echo $this->getChildHtml('flexslider'); ?>
</div>
<a href="<?php echo Mage::getBaseUrl() . 'eyelash-extensions-waxing-facials-microblading-microneedling-hawaii'?>" class='image-pad'>
	<!-- <div class='pad-text'><p>Strip lashes.Falsies</p>
	</div> -->
	<img src="<?php echo $this->getSkinUrl('images/lash_extensions_oahu.jpg', array('_secure'=>true));?>" title="Eyelash Extensions Oahu Honolulu" alt="Lash Extensions Oahu Honolulu| False Eyelashes | Wahiawa | Schofield Barracks | Mililani"/>
	<div>

	</div>
</a>
<a class='image-pad' href="<?php echo Mage::getBaseUrl() . 'menu-eyelash-extensions-facials-waxing-microblading-microneedling#waxing'?>">
	<img src="<?php echo $this->getSkinUrl('images/wax_salon_oahu.jpg', array('_secure'=>true));?>"/>
</a> 

<a class='image-pad' href="<?php echo Mage::getBaseUrl() . 'beauty-products/makeup-brushes/12-piece-makeup-brush-set-with-brush-holder-container.html'?>">
	<img src="<?php echo $this->getSkinUrl('images/makeup_brush.png', array('_secure'=>true));?>"/>
</a>


<a class='image-pad' href="<?php echo Mage::getBaseUrl() . 'eyelash-extensions-waxing-facials-microblading-microneedling-hawaii#skincare'?>">
	<img src="<?php echo $this->getSkinUrl('images/beauty_skin_care_facials.jpg', array('_secure'=>true));?>"/>
</a>
<a class='image-pad' href="<?php echo Mage::getBaseUrl() . 'eyelash-extensions-waxing-facials-microblading-microneedling-hawaii#microblading'?>">
	<img src="<?php echo $this->getSkinUrl('images/phibrows_microblading.jpg', array('_secure'=>true));?>"/>
</a> 
</div>
