<?php 
//echo $this->getChildHtml('flexslider');
echo $this->getChildHtml('categorypad');
echo $this->getChildHtml('new_products');

?>

<div id="instafeed-head"> Instagram: <a href="https://www.instagram.com/pinkysbeautybox/?ref=badge">@pinkysbeautybox</a>
</div>
<div id="instafeed"></div>


<script type="text/javascript">
var userFeed = new Instafeed({
    get: 'user',
    limit: '8',
    resolution: 'low_resolution',
    userId: '2976525140',
    accessToken: '2976525140.1677ed0.5a926e5cddc746e8b378fef352653732',
    template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /></a>'
});
userFeed.run();

</script>
