<?php 
//echo $this->getChildHtml('flexslider');
echo $this->getChildHtml('categorypad');
echo $this->getChildHtml('info_pad');
//echo $this->getChildHtml('new_products');

?>

<div class='embedsocial-hashtag' data-ref="ad5b507f4e1dee83d11d50a487ca09001c56f79f" ></div><script>(function(d, s, id){var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js);}(document, "script", "EmbedSocialHashtagScript"));</script>